---
kind: pipeline
name: amd64_prepare

platform:
  os: linux
  arch: amd64

steps:
  - name: PrepareReports
    image: ubuntu
    depends_on: [ clone ]
    volumes:
      - name: reports
        path: /var/local/dronetests/reports
    commands:
      - sleep 1
      - mkdir --parents /var/local/dronetests/reports/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/${DRONE_RUNNER_PLATFORM}
      - echo "DRONE_BUILD_CREATED ${DRONE_BUILD_CREATED}" > /var/local/dronetests/reports/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/${DRONE_RUNNER_PLATFORM}/drone_report

volumes:
  - name: reports
    host:
      path: /var/local/dronetests/reports
---
kind: pipeline
name: amd64_build

steps:
  - name: Build
    image: ubuntu
    depends_on: [ clone ]
    volumes:
      - name: cache
        path: /tmp
    commands:
      - sleep 1
      - touch apt_report
      - touch cmake_report
      - touch make_report
      - touch unittestsuite1executable
      - touch unittestsuite2executable
      - cp unittestsuite1executable /tmp/unittestsuite1executable
      - cp unittestsuite2executable /tmp/unittestsuite2executable
      - touch integrationtestsuite1aexecutable
      - touch integrationtestsuite1bexecutable
      - touch integrationtestsuite2aexecutable
      - touch integrationtestsuite2bexecutable
      - cp integrationtestsuite1aexecutable /tmp/integrationtestsuite1aexecutable
      - cp integrationtestsuite1bexecutable /tmp/integrationtestsuite1bexecutable
      - cp integrationtestsuite2aexecutable /tmp/integrationtestsuite2aexecutable
      - cp integrationtestsuite2bexecutable /tmp/integrationtestsuite2bexecutable

  - name: GatherBuildReports
    image: ubuntu
    depends_on: [ Build ]
    when:
      status: [ success, failure ]
    volumes:
      - name: reports
        path: /var/local/dronetests/reports
    commands:
      - ls -l
      - cp apt_report /var/local/dronetests/reports/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/${DRONE_RUNNER_PLATFORM}/apt_report
      - cp cmake_report /var/local/dronetests/reports/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/${DRONE_RUNNER_PLATFORM}/cmake_report
      - cp make_report /var/local/dronetests/reports/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/${DRONE_RUNNER_PLATFORM}/make_report

volumes:
- name: cache
  tmp: {}
volumes:
  - name: reports
    host:
      path: /var/local/dronetests/reports

trigger:
  status:
  - success

depends_on:
- amd64_prepare
---
kind: pipeline
name: amd64_unittest

steps:
  - name: PrepareUnitTestSuites
    image: ubuntu
    depends_on: [ clone ]
    volumes:
      - name: cache
        path: /tmp
    commands:
      - sleep 1
      - cp /tmp/unittestsuite1executable unittestsuite1executable
      - cp /tmp/unittestsuite2executable unittestsuite2executable
      - touch prepareunittestsuites_report
      
  - name: UnitTestSuite1a
    image: ubuntu
    depends_on: [ PrepareUnitTestSuites ]
    commands:
      - sleep 1
      - cp unittestsuite1executable unittestsuite1executable_executed
      - touch unittestsuite1_report

  - name: UnitTestSuite2
    image: ubuntu
    depends_on: [ PrepareUnitTestSuites ]
    commands:
      - sleep 1
      - cp unittestsuite2executable unittestsuite2executable_executed
      - touch unittestsuite2_report

  - name: GatherUnitTestSuiteReports
    image: ubuntu
    when:
      status: [ success, failure ]
    depends_on: [ PrepareUnitTestSuites, UnitTestSuite1, UnitTestSuite2 ]
    volumes:
      - name: reports
        path: /var/local/dronetests/reports
    commands:
      - ls -l
      - cp prepareunittestsuites_report /var/local/dronetests/reports/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/${DRONE_RUNNER_PLATFORM}/prepareunittestsuites_report
      - cp unittestsuite1_report /var/local/dronetests/reports/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/${DRONE_RUNNER_PLATFORM}/unittestsuite1_report
      - cp unittestsuite2_report /var/local/dronetests/reports/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/${DRONE_RUNNER_PLATFORM}/unittestsuite2_report

volumes:
- name: cache
  tmp: {}
volumes:
  - name: reports
    host:
      path: /var/local/dronetests/reports

trigger:
  status:
  - success

depends_on:
- amd64_build
